name: Code Quality Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run custom code review
      run: node scripts/code-review.js
    
    - name: Check bundle size
      run: |
        npm run build
        npx bundlesize
    
    - name: Run performance audit
      run: npm run audit:performance
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('code-quality-report.json', 'utf8');
          const data = JSON.parse(report);
          
          const comment = `
          ## 🔍 Code Quality Report
          
          - **Errors:** ${data.errors}
          - **Warnings:** ${data.warnings}  
          - **Score:** ${data.score}/100
          
          ${data.score < 70 ? '🔴 **Action Required:** Quality too low' : ''}
          ${data.score >= 85 ? '🟢 **Great job!** Good code quality' : ''}
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });